name: Deploy to AWS EC2

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install Docker and Docker Compose
        run: |
          sudo yum update -y
          sudo amazon-linux-extras install docker
          sudo service docker start
          sudo usermod -a -G docker ec2-user
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Clone Github repository
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.226.15.234 "git clone git@github.com:superdesk/video-server-app.git"

      - name: Build and run Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.226.15.234 "cd video-server-app && sudo docker-compose up -d"
